const { chromium } = require("playwright");
//const { getReportData } = require("./reportData");

function buildHtml(report) {
  const today = new Date().toISOString().split("T")[0];

  const topProductsRows = report.topProducts
    .map(
      (item, index) => `
        <tr>
          <td>${index + 1}</td>
          <td>${item.product}</td>
          <td>$${Number(item.revenue).toFixed(2)}</td>
        </tr>
      `
    )
    .join("");

  const ordersPerDayRows = report.ordersPerDay
    .map(
      (item) => `
        <tr>
          <td>${item.created_at}</td>
          <td>${item.orderCount}</td>
        </tr>
      `
    )
    .join("");

  // Extra rows make the PDF long enough to test page breaks.
  const allOrdersRows = report.allOrders
    ? report.allOrders
        .map(
          (order) => `
            <tr>
              <td>${order.id}</td>
              <td>${order.customer}</td>
              <td>${order.product}</td>
              <td>$${Number(order.amount).toFixed(2)}</td>
              <td>${order.created_at}</td>
            </tr>
          `
        )
        .join("")
    : "";

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8" />

      <style>
        @page {
          size: A4;
          margin: 20mm;
        }

        body {
          font-family: Arial, sans-serif;
          color: #222;
          line-height: 1.5;
        }

        h1 {
          margin-bottom: 5px;
        }

        .date {
          color: #666;
          margin-bottom: 25px;
        }

        .summary {
          display: flex;
          gap: 20px;
          margin-bottom: 30px;
        }

        .card {
          border: 1px solid #ddd;
          padding: 15px;
          width: 200px;
        }

        .card-title {
          color: #666;
          font-size: 13px;
        }

        .card-value {
          font-size: 24px;
          font-weight: bold;
          margin-top: 5px;
        }

        h2 {
          margin-top: 30px;
          border-bottom: 2px solid #333;
          padding-bottom: 5px;
        }

        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 10px;
        }

        th,
        td {
          border: 1px solid #ccc;
          padding: 8px;
          text-align: left;
        }

        th {
          background: #f2f2f2;
        }

        thead {
          display: table-header-group;
        }

        tr {
          break-inside: avoid;
        }

        .footer {
          margin-top: 30px;
          color: #777;
          font-size: 12px;
        }
      </style>
    </head>

    <body>
      <h1>Sales Report</h1>
      <div class="date">Generated on ${today}</div>

      <div class="summary">
        <div class="card">
          <div class="card-title">Total Orders</div>
          <div class="card-value">${report.totalOrders}</div>
        </div>

        <div class="card">
          <div class="card-title">Total Revenue</div>
          <div class="card-value">
            $${Number(report.totalRevenue).toFixed(2)}
          </div>
        </div>
      </div>

      <h2>Top 5 Products by Revenue</h2>

      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>Product</th>
            <th>Revenue</th>
          </tr>
        </thead>

        <tbody>
          ${topProductsRows}
        </tbody>
      </table>

      <h2>Orders per Day — Last 7 Days</h2>

      <table>
        <thead>
          <tr>
            <th>Date</th>
            <th>Orders</th>
          </tr>
        </thead>

        <tbody>
          ${ordersPerDayRows}
        </tbody>
      </table>

      <h2>All Orders</h2>

      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Customer</th>
            <th>Product</th>
            <th>Amount</th>
            <th>Date</th>
          </tr>
        </thead>

        <tbody>
          ${allOrdersRows}
        </tbody>
      </table>

      <div class="footer">
        Generated by the FlyRank PDF Report Generator.
      </div>
    </body>
    </html>
  `;
}

async function generatePdf(report, outputPath) {
  const browser = await chromium.launch();

  try {
    const page = await browser.newPage();

    const html = buildHtml(report);

    await page.setContent(html);

    await page.pdf({
      path: outputPath,
      format: "A4",
      printBackground: true
    });

    console.log(`PDF generated: ${outputPath}`);
  } finally {
    await browser.close();
  }
}

module.exports = {
  buildHtml,
  generatePdf
};
// generatePdf().catch((error) => {
//   console.error("Failed to generate PDF:", error);
//   process.exit(1);
// });